### ISSUE TITLE
Bug Report 

### ISSUE THREAD

**Issue by SoundWavez97** [legend-js-dev/anti-raid#1]
Line 534 in index the
.then(lolxd.....

Has error cannot read property then of undefined

**Comment by AstaGotBandzz** [comment]
Same issue as ChillNotTaken

**Comment by AzanCodesOnGitHub** [comment]
shit thats bc its an ip logger u smart guy lol

**Comment by legend-js-dev** [comment]
no? Are you dumb or what, there’s no ip logger in it, and you are not allowed to use the src cuz it’s for boosters only, and if you do use it then you shall face the consequences like getting a copyright strike, etc. i didn’t exactly mean to put the src on GitHub but eh yea

**Comment by SoundWavez97** [comment]
> no? Are you dumb or what, there’s no ip logger in it, and you are not allowed to use the src cuz it’s for boosters only, and if you do use it then you shall face the consequences like getting a copyright strike, etc. i didn’t exactly mean to put the src on GitHub but eh yea

bruh i dont even use it, i just found an error and reported it....

**Comment by legend-js-dev** [comment]
was just saying it in case you were using it.
