### ISSUE TITLE
Client missing intent error 

### ISSUE THREAD

**Issue by DevRedant** [legend-js-dev/anti-raid#3]
I have enabled all intent but the error says intent not enabled.
![Screenshot_2024-03-30-04-22-48-338](https://github.com/legend-js-dev/anti-raid/assets/74412037/35df4d1d-9fc9-4797-b4ab-ced86e119c8b)

**Comment by legend-js-dev** [comment]
This code was written when intents were not a thing in discord, so if you want to use it you'll have to update the code accordingly for it
